# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
    shield: cornix_dongle_adapter cornix_dongle_eyelash dongle_display
    snippet: studio-rpc-usb-uart nrf52840-nosd
    artifact-name: cornix_dongle_nosd
  - board: seeeduino_xiao_ble
    shield: cornix_dongle_adapter dongle_screen
    snippet: studio-rpc-usb-uart
    artifact-name: cornix_dongle_screen_xiao
  - board: nice_nano_v2
    shield: cornix_dongle_adapter dongle_screen
    snippet: studio-rpc-usb-uart
    artifact-name: cornix_dongle_screen_nicenano

  - board: cornix_left
    #shield: cornix_indicator
    artifact-name: cornix_left_default_nosd

  - board: cornix_ph_left
    #shield: cornix_indicator
    artifact-name: cornix_left_for_dongle_nosd

  - board: cornix_right
    #shield: cornix_indicator
    artifact-name: cornix_right_nosd

  - board: cornix_right
    shield: settings_reset
    artifact-name: reset

  - board: cornix_right
    shield: settings_reset
    snippet: studio-rpc-usb-uart nrf52840-nosd
    artifact-name: reset_nosd
